### ISSUE TITLE
Change default page

### ISSUE THREAD

**Issue by thehitechpanky** [smilyo/Smilyo-Beta--Android#12]
Instead of mere logo it should show what we're doing and an option to donate

**Comment by yogeshmadaan100** [comment]
Any Suggestions ?

**Comment by thehitechpanky** [comment]
Just show the content of ngo.smilyo.com/donate

**Comment by yogeshmadaan100** [comment]
ok will do that...review current request.

**Comment by yogeshmadaan100** [comment]
@thehitechpanky  we will need a web view to display it.. Are you ok with it?

**Comment by thehitechpanky** [comment]
No need of web view... We just want to display some text in there...at most a PIC...

Either pull in content as we're doing for articles or give me a window where I can add such text to display on home page....
