### ISSUE TITLE
Unicode Characters

### ISSUE THREAD

**Issue by yogeshmadaan100** [smilyo/Smilyo-Beta--Android#8]
The articles and poems show unnecessary unicode characters

**Comment by yogeshmadaan100** [comment]
U need help in wat context?.. Pull request

**Comment by thehitechpanky** [comment]
Yes please

**Comment by yogeshmadaan100** [comment]
Ok Pankaj,

I will do the needful asap. Till then please review my current pull request.

**Comment by thehitechpanky** [comment]
Thanks yogesh, tarun is reviewing the current pull request.

**Comment by yogeshmadaan100** [comment]
@tarun550 @thehitechpanky  Please review :)
